// <auto-generated />
using FloraTransAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FloraTransAPI.Migrations
{
    [DbContext(typeof(FloraTransAPIContext))]
    partial class FloraTransAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FloraTransAPI.Models.Bevægelser", b =>
                {
                    b.Property<int>("BID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KundeID")
                        .HasColumnType("int");

                    b.Property<int>("LagerID")
                        .HasColumnType("int");

                    b.Property<string>("afleveretDato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sendtAntalHylder")
                        .HasColumnType("int");

                    b.Property<int>("sendtAntalSøjlerør")
                        .HasColumnType("int");

                    b.Property<int>("sendtBundramme")
                        .HasColumnType("int");

                    b.Property<string>("tilbagemodtagetDato")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BID");

                    b.HasIndex("KundeID");

                    b.HasIndex("LagerID");

                    b.ToTable("Bevægelser");

                    b.HasData(
                        new
                        {
                            BID = 1,
                            KundeID = 1,
                            LagerID = 4,
                            afleveretDato = "24/04/2021",
                            sendtAntalHylder = 5,
                            sendtAntalSøjlerør = 4,
                            sendtBundramme = 1,
                            tilbagemodtagetDato = "20/05/2021"
                        },
                        new
                        {
                            BID = 2,
                            KundeID = 1,
                            LagerID = 2,
                            afleveretDato = "05/06/2021",
                            sendtAntalHylder = 5,
                            sendtAntalSøjlerør = 4,
                            sendtBundramme = 1,
                            tilbagemodtagetDato = "05/07/2021"
                        },
                        new
                        {
                            BID = 3,
                            KundeID = 2,
                            LagerID = 2,
                            afleveretDato = "18/08/2021",
                            sendtAntalHylder = 3,
                            sendtAntalSøjlerør = 4,
                            sendtBundramme = 1,
                            tilbagemodtagetDato = "18/09/2021"
                        },
                        new
                        {
                            BID = 4,
                            KundeID = 2,
                            LagerID = 5,
                            afleveretDato = "18/04/2021",
                            sendtAntalHylder = 5,
                            sendtAntalSøjlerør = 4,
                            sendtBundramme = 1,
                            tilbagemodtagetDato = "18/05/2021"
                        },
                        new
                        {
                            BID = 5,
                            KundeID = 3,
                            LagerID = 3,
                            afleveretDato = "15/08/2021",
                            sendtAntalHylder = 5,
                            sendtAntalSøjlerør = 4,
                            sendtBundramme = 1,
                            tilbagemodtagetDato = "15/09/2021"
                        });
                });

            modelBuilder.Entity("FloraTransAPI.Models.Fejlmeldinger", b =>
                {
                    b.Property<int>("FID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BevægelserID")
                        .HasColumnType("int");

                    b.Property<bool>("HeltTabt")
                        .HasColumnType("bit");

                    b.Property<int>("manglerAntalHylder")
                        .HasColumnType("int");

                    b.Property<int>("manglerAntalSøjlerør")
                        .HasColumnType("int");

                    b.Property<int>("manglerBundramme")
                        .HasColumnType("int");

                    b.HasKey("FID");

                    b.HasIndex("BevægelserID");

                    b.ToTable("Fejlmeldinger");

                    b.HasData(
                        new
                        {
                            FID = 2,
                            BevægelserID = 1,
                            HeltTabt = false,
                            manglerAntalHylder = 3,
                            manglerAntalSøjlerør = 0,
                            manglerBundramme = 0
                        },
                        new
                        {
                            FID = 3,
                            BevægelserID = 4,
                            HeltTabt = true,
                            manglerAntalHylder = 5,
                            manglerAntalSøjlerør = 4,
                            manglerBundramme = 1
                        });
                });

            modelBuilder.Entity("FloraTransAPI.Models.Kunder", b =>
                {
                    b.Property<int>("KID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CVRNR")
                        .HasColumnType("int");

                    b.Property<string>("adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jobtitel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("navn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KID");

                    b.ToTable("Kunder");

                    b.HasData(
                        new
                        {
                            KID = 1,
                            CVRNR = 436734278,
                            adresse = "Landmarksgade 43",
                            email = "MarkMail@hotmail.com",
                            jobtitel = "Landmand",
                            navn = "Mark",
                            telefon = "45 63 27 18"
                        },
                        new
                        {
                            KID = 2,
                            CVRNR = 736734278,
                            adresse = "Pcvejle 42",
                            email = "JohnMail@hotmail.com",
                            jobtitel = "Youtuber",
                            navn = "John",
                            telefon = "Ukendt"
                        },
                        new
                        {
                            KID = 3,
                            CVRNR = 436734278,
                            adresse = "Landmarksgade 43",
                            email = "JulieMail@hotmail.com",
                            jobtitel = "Forfatter",
                            navn = "Julie",
                            telefon = "47 43 97 98"
                        });
                });

            modelBuilder.Entity("FloraTransAPI.Models.Lager", b =>
                {
                    b.Property<int>("LID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("antalhylder")
                        .HasColumnType("int");

                    b.Property<int>("antalsøjlerør")
                        .HasColumnType("int");

                    b.Property<float>("brugsretten")
                        .HasColumnType("real");

                    b.Property<int>("bundramme")
                        .HasColumnType("int");

                    b.Property<bool>("ledighed")
                        .HasColumnType("bit");

                    b.Property<string>("lejeDato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("udløbsDato")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LID");

                    b.ToTable("Lager");

                    b.HasData(
                        new
                        {
                            LID = 1,
                            antalhylder = 5,
                            antalsøjlerør = 4,
                            brugsretten = 1500.49f,
                            bundramme = 1,
                            ledighed = true,
                            lejeDato = "16/08/2021",
                            udløbsDato = "16/08/2022"
                        },
                        new
                        {
                            LID = 2,
                            antalhylder = 5,
                            antalsøjlerør = 4,
                            brugsretten = 1500.49f,
                            bundramme = 1,
                            ledighed = false,
                            lejeDato = "15/03/2021",
                            udløbsDato = "15/03/2022"
                        },
                        new
                        {
                            LID = 3,
                            antalhylder = 5,
                            antalsøjlerør = 4,
                            brugsretten = 1500.49f,
                            bundramme = 1,
                            ledighed = false,
                            lejeDato = "03/01/2021",
                            udløbsDato = "03/01/2022"
                        },
                        new
                        {
                            LID = 4,
                            antalhylder = 2,
                            antalsøjlerør = 4,
                            brugsretten = 1500.49f,
                            bundramme = 1,
                            ledighed = false,
                            lejeDato = "01/01/2021",
                            udløbsDato = "01/01/2022"
                        },
                        new
                        {
                            LID = 5,
                            antalhylder = 0,
                            antalsøjlerør = 0,
                            brugsretten = 1500.49f,
                            bundramme = 0,
                            ledighed = false,
                            lejeDato = "01/01/2021",
                            udløbsDato = "01/01/2022"
                        });
                });

            modelBuilder.Entity("FloraTransAPI.Models.Bevægelser", b =>
                {
                    b.HasOne("FloraTransAPI.Models.Kunder", "Kunde")
                        .WithMany()
                        .HasForeignKey("KundeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FloraTransAPI.Models.Lager", "Lager")
                        .WithMany()
                        .HasForeignKey("LagerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kunde");

                    b.Navigation("Lager");
                });

            modelBuilder.Entity("FloraTransAPI.Models.Fejlmeldinger", b =>
                {
                    b.HasOne("FloraTransAPI.Models.Bevægelser", "Bevægelser")
                        .WithMany()
                        .HasForeignKey("BevægelserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bevægelser");
                });
#pragma warning restore 612, 618
        }
    }
}
